name: Generate custom-rules.lst/getdomains custom-rules_raw.lst/podkop
on:
  schedule:
    - cron: "10 0 * * *"  # Запуск в 00:10 каждый день
  workflow_dispatch: # Ручной запуск

jobs:
  update-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install --upgrade pip requests

    - name: Run merge script
      run: python generate_customrules_lst.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add custom-rules.lst custom-rules_raw.lst
        git commit -m "Update LST files" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
